---
name: islam_made_easy
description: Islamic  application that let you understand your religion easier.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.3
  hijri: null
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  provider: ^5.0.0
  font_awesome_flutter: ^9.0.0
  share: ^2.0.1
  lottie: null
  flutter_easyrefresh: null
  dio: null
  intl: ^0.17.0-nullsafety.2
  flutter_animated_dialog: any
  flutter_statusbarcolor: null
  universal_html: null
  sqflite: null
  sp_util: ^2.0.3
  shared_preferences: ^2.0.5
  json_annotation: null
  random_string: null
  cached_network_image: null
  flutter_staggered_grid_view: null
  http: null
  path: null
  url_launcher: null
  animated_background: null
  flutter_phoenix: null
  smooth_page_indicator: null
  flutter_flip_view: null
  universal_platform: null
  adaptive_breakpoints: ^0.0.2
  get: ^4.1.4
  package_info: null
  launch_review: null
  animations: ^2.0.0
  flutter_svg: ^0.22.0
  native_pdf_view: ^4.0.1
  delayed_display: ^2.0.0
  double_back_to_close: ^2.0.0
  quick_actions: ^0.6.0+1
  flutter_systray: ^0.4.0
  avatar_glow: ^2.0.1
  animator: null
  clippy_flutter: null
  grafpix: null
  animated_text_kit: null
  popover: ^0.2.3
  auto_size_text: null
  shimmer: ^2.0.0
  flutter_local_notifications: ^5.0.0+4
  markdown: null
  flutter_markdown: null
  bubble_overlay:
  system_alert_window:
  url_strategy:
  animate_do:
  desktop_window:
  bitsdojo_window:
  syncfusion_flutter_pdfviewer:
  chewie:
  ext_storage:
          # flutter_ffmpeg:
  flutter_vlc_player:
  fuzzy:
  lazy_load_scrollview:
  permission_handler:
  subtitle_wrapper_package:
  transparent_image:
  youtube_player_flutter:
  wakelock:
  firebase_storage:
  firebase_core:
#  firebase_analytics:
  firebase:
  better_player: ^0.0.13
  gsheets: ^0.3.0
  statsfl:
  starflut:
dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4
  flutter_test:
    sdk: flutter
  build_runner: null
  json_serializable: null
# SPLASH SCREEN GENERATOR
flutter_native_splash:
  image: assets/images/logo.png
  color: "111111"

# ICON GENERATOR
flutter_icons:
  android: "ic_launcher"
  image_path_android: "assets/images/logo.png"
  ios: true
  image_path_ios: "assets/images/logo.png"
flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/lottie/
  - assets/quiz/
  - assets/fonts/
  - assets/md/
  - assets/icons/
  - assets/daily/
flutter_intl:
  enabled: true
  fonts:
  - family: Amiri
    fonts:
    - asset: assets/fonts/Amiri-Regular.ttf
    - asset: assets/fonts/Amiri-Bold.ttf
  - family: KFGQPC Uthman Taha Naskh
    fonts:
    - asset: assets/fonts/uthman_tn09.otf
  - family: ReemKufi
    fonts:
    - asset: assets/fonts/ReemKufi-Regular.tff
  - family: Quattrocento
    fonts:
    - asset: assets/fonts/Quattrocento-Regular.ttf
    - asset: assets/fonts/Quattrocento-Bold.ttf
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto-Regular.ttf
      - asset: assets/fonts/Roboto-Light.ttf
      - asset: assets/fonts/Roboto-Thin.ttf
      - asset: assets/fonts/Roboto-Bold.ttf
